### ISSUE TITLE
Data availability for running reproducibility code (`Figure5.ipynb`)

### ISSUE THREAD

**Issue by zoepiran** [nolanlab/TissueSchematics#1]
Hi, we are very inspired by your work and wanted to use the code and provided analysis. However, trying to run `[Figure5.ipynb](https://github.com/nolanlab/TissueSchematics/blob/main/ipynb/Figure5%20.ipynb)`  we realized some of the data files are missing.

We thought that maybe `[CRC_clusters_neighborhoods_markers.csv](https://data.mendeley.com/datasets/mpjzbtfgfr/1)` could be used instead of `'submissiondata/cells2_salil'` and that `[CRC_TMAs_patient_annotations.xlsx](https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=70227790)`  can be used for `crc_patient_surv.csv`. 
The analysis seemed consistent for results depending on the former (`CRC_clusters_neighborhoods_markers.csv`). However, adding the latter for section `Assessing Survival wrt 047` we cant seem to reproduce reported results. 
Thank you in advance

**Comment by salilb1** [comment]
Hi there! Thanks so much for your interest in our work.  I'll definitely update the readme with links to those files. 

As regards the survival analysis, I just checked that the corresponding columns from 'CRC_TMAs_patient_annotations.xlsx' are the same as those in the 'crc_patient_surv.csv' utilized in the notebook. Was there an error thrown when running the code or was the output different from that in the submitted notebook? 

Thanks a lot for highlighting this issue!

Salil

**Comment by zoepiran** [comment]
Hi,
Amazing, thank you :)
No errors were thrown however the outputs are different (attached).

![image](https://user-images.githubusercontent.com/43661890/143877729-a0aaae84-bb05-4110-adbf-4147ff52e4c8.png)

![image](https://user-images.githubusercontent.com/43661890/143877697-8eb9181d-0618-4859-a132-a4ade96b4672.png)

![image](https://user-images.githubusercontent.com/43661890/143877668-20e7a339-48b6-4667-a7de-e9ce3b675b74.png)

**Comment by salilb1** [comment]
How strange - there must be a discrepancy further up - thanks so much for your help in debugging this! 

Could you post a screenshot of the 'gp2' dataframe generated in the third cell after 'assessing survival wrt t047'?

Salil

**Comment by salilb1** [comment]
Quick update: I re-ran the notebook using the files from TCIA and Mendeley and the results were the same as reported (I pushed this as https://github.com/nolanlab/TissueSchematics/blob/main/ipynb/Figure5-schuerch-data.ipynb)

Did you by any chance update the notebooks when you were attempting to reproduce these analyses? If so, could you please try running the Figure5-schuerch-data.ipynb notebook? If there is still a discrepancy, perhaps there could be some package versioning issues? At any rate I think the gp2 dataframe is a good starting point.

Thanks,
Salil

**Comment by zoepiran** [comment]
Hi, 

please excuse me for the delay. 
Thank you - I am capable of reproducing the results now :) 
(I am quite embarrassed to say it seems like my mistake was *very* stupid - importing the `CRC_TMAs_patient_annotations.xlsx` file I didn't use `pd`s read_xlsx but tried to locally convert to `csv` on my mac prior to that and didn't index by `Patient` so i guess some values didn't pass properly as numeric)

Thank you again for the prompt response!

**Comment by salilb1** [comment]
No worries at all!! Honestly it's great to have someone trying out the code, and I should have definitely worked with the publicly available data to start with.

Salil
